version: 2

registries:
  maven-github:
    type: maven-repository
    url: https://maven.pkg.github.com/heyrmi
    username: heyrmi
    password: ${{secrets.ARTIFACTORY_PASSWORD}}

updates:
  - package-ecosystem: github-actions
    directory: /
    open-pull-requests-limit: 2
    rebase-strategy: auto
    schedule:
      interval: weekly
      day: sunday
      time: "05:00"
      timezone: "Asia/Calcutta"

  - package-ecosystem: maven
    directory: /
    registries:
      - maven-github
    open-pull-requests-limit: 2
    rebase-strategy: auto
    schedule:
      interval: weekly
      day: sunday
      time: "05:00"
      timezone: "Asia/Calcutta"

  - package-ecosystem: gitsubmodule
    directory: /
    registries:
      - maven-github
    schedule:
      interval: weekly
      day: sunday
      time: "05:00"
